#.github/workflows/publish.yml
name: Render dan Deploy Quarto files

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Penting: Berikan izin tulis untuk GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python dependencies (jika produk menggunakan Python)
        run: |
          pip install -r requirements.txt # Pastikan ada file requirements.txt jika menggunakan Python

      - name: Render dan Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # Target branch untuk GitHub Pages
          # token: ${{ secrets.GITHUB_TOKEN }} # Token default sudah cukup